language: bash
before_script:
  - mkdir -p /tmp/bin
  - wget https://github.com/cedric-vincent/proot-static-build/raw/master/static/proot-x86_64 -O /tmp/bin/proot
  - chmod +x /tmp/bin/proot
  - export PATH=$PATH:/tmp/bin
install:
  - mv $(pwd) /home/travis
  - cd /home/travis/dotfiles
  - cat $HOME/.gitconfig
  - cat $HOME/.zshrc
  - mkdir $HOME/root_nix
  - rm $HOME/.zshrc $HOME/.gitconfig
  - sed -i 's#git@github.com:#https://github.com/#g' myrepos/.mrconfig
script:
  - proot -R $HOME/root_nix ./tests/prootfull.sh
sudo: false
