language: bash
before_script:
  - mkdir -p /tmp/bin
  - wget https://github.com/cedric-vincent/proot-static-build/raw/master/static/proot-x86_64 -O /tmp/bin/proot
  - chmod +x /tmp/bin/proot
  - export PATH=$PATH:/tmp/bin
install:
  - mkdir -p $HOME/root_nix/{nix,home/travis}
  - mv $(pwd) $HOME/root_nix/home/travis/
  - cd $HOME/root_nix/home/travis/dotfiles
  - sed -i 's#git@github.com:#https://github.com/#g' myrepos/.mrconfig
script:
  - proot -b $HOME/root_nix/nix:/nix -b $HOME/root_nix/home:/home -w /home/travis/dotfiles /home/travis/dotfiles/tests/prootfull.sh
sudo: false
