language: bash
install:
  - sudo apt-get purge emacs
  - mv $(pwd) /home/travis
  - cd /home/travis/dotfiles
  - cat $HOME/.gitconfig
  - cat $HOME/.zshrc
  - rm $HOME/.zshrc $HOME/.gitconfig
  - sed -i 's#git@github.com:#https://github.com/#g' myrepos/.mrconfig
  - ./install.sh
script:
  - source $HOME/.nix-profile/etc/profile.d/nix.sh && ./uninstall.sh
sudo: required
addons:
  apt:
    packages:
    - zsh
