language: bash
install:
  - mv $(pwd) /home/travis
  - cd /home/travis/dotfiles
  - sed -i 's#git@github.com:#https://github.com/#g' myrepos/.mrconfig
  - ./install.sh
script:
  - ./uninstall.sh
sudo: required
addons:
  apt:
    packages:
    - zsh
